version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data-volume:/root/internal/database/
    ports:
      - "3000:3000"
      - "8080:8080"
volumes:
  data-volume: