POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "login": "admin",
    "password": "admin"
}

###

POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "login": "admin",
    "password": "admin"
}

###
GET http://localhost:3000/api/v1/get-expressions
Authorization: Bearer {{jwt}}

###
POST http://localhost:3000/api/v1/add-expression
Authorization: Bearer {{jwt}}
Content-Type: text/plain

2+2

###
GET http://localhost:3000/api/v1/get-value/2
Authorization: Bearer {{jwt}}

###
GET http://localhost:3000/api/v1/get-operations

###
